"""Add Razorpay payment fields to Order

Revision ID: d4233d8b9c75
Revises: 353b392a00fe
Create Date: 2025-12-06 08:19:44.050310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4233d8b9c75'
down_revision = '353b392a00fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pickup_ready', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('razorpay_order_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('payment_amount')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('razorpay_payment_id')
        batch_op.drop_column('razorpay_order_id')
        batch_op.drop_column('pickup_ready')
        batch_op.drop_column('table_number')

    # ### end Alembic commands ###
